### ISSUE TITLE
Compile error g++-4.4

### ISSUE THREAD

**Issue by fvella** [adampolak/triangles#1]
Hi Adam,

I am trying to compile your code. 
I'm using g++ 4.4.6-4 version and compile with your Makefile

g++ -std=c++0x -O3 -fno-stack-protector convert-from-dimacs-main.cpp graph.cpp -o convert-from-dimacs-main.e 
The error is the following:

graph.cpp: In function ‘int NumVertices(const Edges&)’:
graph.cpp:73: error: expected initializer before ‘:’ token
graph.cpp:75: error: expected primary-expression before ‘return’
graph.cpp:75: error: expected ‘;’ before ‘return’
graph.cpp:75: error: expected primary-expression before ‘return’
graph.cpp:75: error: expected ‘)’ before ‘return’
graph.cpp: In function ‘void PermuteVertices(Edges_)’:
graph.cpp:110: error: expected initializer before ‘:’ token
graph.cpp:114: error: expected primary-expression before ‘}’ token
graph.cpp:114: error: expected ‘;’ before ‘}’ token
graph.cpp:114: error: expected primary-expression before ‘}’ token
graph.cpp:114: error: expected ‘)’ before ‘}’ token
graph.cpp:114: error: expected primary-expression before ‘}’ token
graph.cpp:114: error: expected ‘;’ before ‘}’ token
graph.cpp: In function ‘AdjList EdgesToAdjList(const Edges&)’:
graph.cpp:120: error: expected initializer before ‘:’ token
graph.cpp:122: error: expected primary-expression before ‘return’
graph.cpp:122: error: expected ‘;’ before ‘return’
graph.cpp:122: error: expected primary-expression before ‘return’
graph.cpp:122: error: expected ‘)’ before ‘return’
make: *_\* [convert-from-dimacs-main.e] Error 1

Best,
Flavio

**Comment by adampolak** [comment]
Hi Flavio,

according to https://gcc.gnu.org/projects/cxx0x.html you need at least g++
4.6 for range-based for support which I use in my code.

Adam

2015-03-04 19:54 GMT+01:00 Flavio Vella notifications@github.com:

**Comment by fvella** [comment]
Thanks,
works!
